base: '%env(TYPO3_BASE_DOMAIN)%'
dependencies:
  - typo3-incubator/theme-fcbigfoot
  - typo3-incubator/memsy/member-management
  - typo3/felogin
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: 'FC Bigfoot'
