base: '%env(SITE_FCBIGFOOT_BASE)%'
dependencies:
  - typo3-incubator/theme-fcbigfoot
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: 'FC Bigfoot'
