services:
  typo3:
    image: ghcr.io/ochorocho/surfcamp-extensions-2025:latest
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - "3306:3306"
    volumes:
      - surfcamp-mariadb-data:/var/lib/mysql

volumes:
  surfcamp-mariadb-data:
