name: Renovate

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM UTC
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Renovate
        uses: renovatebot/github-action@v42.0.2
        with:
          configurationFile: .github/renovate.json
          autodiscover: true
          token: ${{ secrets.RENOVATE_TOKEN }}
          args: >
            --autodiscover
            --platform=github
            --log-level=debug
